version: "2.0"
services:

  webshell:
    container_name: "webshell"
    image: node:latest
    command: "/app/runincontainer.sh"
    working_dir: /app
    network_mode: "host"
    # ports:
    #   - "7000:5173"
    volumes:
      - "./frontend:/app"
