version: "2.0"
services:

  boilerplate:
    container_name: "boilerplate"
    image: node
    command: "/app/runincontainer.sh"
    working_dir: /app
    ports:
      - "13080:5173"
    volumes:
      - "./frontend:/app"
