version: "2.0"
services:

  firestoreinterface:
    container_name: "firestoreinterface"
    image: node:latest
    command: "/app/runincontainer.sh"
    working_dir: /app
    ports:
      - "12080:5173"
    volumes:
      - "./frontend:/app"
