version: "2.0"
services:

  dockerservicename:
    container_name: "dockercontainername"
    image: node:latest
    command: "/app/runincontainer.sh"
    working_dir: /app
    network_mode: "host"
    #ports:
    #  - "15000:5173"
    volumes:
      - "./frontend:/app"
